repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
      - '--max-line-length=120'
